### **Assignment: Understanding Data Preprocessing**

#### **Objective :**
In this assignment, you will learn how to analyze a dataset and determine the appropriate preprocessing technique for each feature before writing any preprocessing code (let's stick to tabular data for now).

In [2]:

import pandas as pd

df = pd.DataFrame({

    "Age":[18,22,25,28,30,35,40,45,50,55],

    "Salary":[25000,28000,32000,35000,42000,
              48000,55000,65000,72000,500000],

    "Experience":[0,1,2,3,5,7,10,12,15,20],

    "Gender":[
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Education":[
        "High School","Bachelor","Bachelor",
        "Master","Master","PhD",
        "Bachelor","Master","PhD","PhD"
    ],

    "City":[
        "Hyderabad","Delhi","Mumbai","Delhi",
        "Hyderabad","Chennai","Mumbai",
        "Delhi","Hyderabad","Chennai"
    ]
})
df

   Age  Salary  Experience  Gender    Education       City
0   18   25000           0    Male  High School  Hyderabad
1   22   28000           1  Female     Bachelor      Delhi
2   25   32000           2    Male     Bachelor     Mumbai
3   28   35000           3  Female       Master      Delhi
4   30   42000           5    Male       Master  Hyderabad
5   35   48000           7  Female          PhD    Chennai
6   40   55000          10    Male     Bachelor     Mumbai
7   45   65000          12  Female       Master      Delhi
8   50   72000          15    Male          PhD  Hyderabad
9   55  500000          20  Female          PhD    Chennai

### **Step 1 Explore the Dataset**

Before performing any preprocessing, explore the dataset.

Complete the following tasks:

1) Display the first five rows.
2) Display the last five rows.
3) Display the shape of the dataset.
4) Display the data types of every column.

In [3]:
# 1 Display the first five rows
df.head()

   Age  Salary  Experience  Gender    Education       City
0   18   25000           0    Male  High School  Hyderabad
1   22   28000           1  Female     Bachelor      Delhi
2   25   32000           2    Male     Bachelor     Mumbai
3   28   35000           3  Female       Master      Delhi
4   30   42000           5    Male       Master  Hyderabad

In [4]:
# 2 Display last five rows
df.tail()

   Age  Salary  Experience  Gender Education       City
5   35   48000           7  Female       PhD    Chennai
6   40   55000          10    Male  Bachelor     Mumbai
7   45   65000          12  Female    Master      Delhi
8   50   72000          15    Male       PhD  Hyderabad
9   55  500000          20  Female       PhD    Chennai

In [5]:
# 3 Display the shape of the dataset.
df.shape

(10, 6)

In [6]:
# 4 Display the data types of every column.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         10 non-null     int64
 1   Salary      10 non-null     int64
 2   Experience  10 non-null     int64
 3   Gender      10 non-null     object
 4   Education   10 non-null     object
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

### **Step 2 Understand the Features**

Now carefully analyze the dataset and answer the following questions.

1) How many numerical features are present?

2) How many categorical features are present?

3) Which feature contains the largest numerical values?

4) Do all numerical features have the same range?

5) Why could different feature scales become a problem for certain Machine Learning algorithms?

In [7]:
# 1) How many numerical features are present?
# A) 3 Numerical features are there in data


# 2) How many categorical features are present?
# A) 3 Categorical features are there in data

# 3) Which feature contains the largest numerical values?
# A) salary has the highest numerical value

# 4) Do all numerical features have the same range?
# A) No all the Numerical features are not in same range

# 5) Why could different feature scales become a problem for certain Machine Learning algorithms
# A) Different feature scales can cause problems because some Machine Learning algorithms calculate distances, gradients, or coefficients. If one feature has much larger values than another, it can dominate the learning process, even if it is not more important.

### **Step 3 Identify Feature Types**

Separate the dataset into

1) Numerical Features
2) Categorical Features

Then answer the following.


1) Which numerical feature has the largest range?

2) Which numerical feature appears to contain an outlier?

3) Which categorical feature is Binary?

4) Which categorical feature is Ordinal?

5) Which categorical feature is Nominal?

In [8]:
# Separate the dataset
numerical_features = df.select_dtypes(include=['int64'])
categorical_features = df.select_dtypes(include=['object'])

In [9]:
# 1 Which numerical feature has the largest range?

numerical_features

# Salary has largest range

   Age  Salary  Experience
0   18   25000           0
1   22   28000           1
2   25   32000           2
3   28   35000           3
4   30   42000           5
5   35   48000           7
6   40   55000          10
7   45   65000          12
8   50   72000          15
9   55  500000          20

In [10]:
# 2 Which numerical feature appears to contain an outlier?
import numpy as np

# Calculate the IQR for each numerical feature
Q1 = numerical_features.quantile(0.25)
Q3 = numerical_features.quantile(0.75)
IQR = Q3 - Q1
q1 = Q1 - 1.5 * IQR
q3 = Q3 + 1.5 * IQR
outliers = numerical_features[(numerical_features < q1) | (numerical_features > q3)]
outliers

# salary has one outlier

   Age    Salary  Experience
0  NaN       NaN         NaN
1  NaN       NaN         NaN
2  NaN       NaN         NaN
3  NaN       NaN         NaN
4  NaN       NaN         NaN
5  NaN       NaN         NaN
6  NaN       NaN         NaN
7  NaN       NaN         NaN
8  NaN       NaN         NaN
9  NaN  500000.0         NaN

In [11]:
# 3) Which categorical feature is Binary?
# A) Gender category is Binary

# 4) Which categorical feature is Ordinal?
# A) Education is ordinal

# 5) Which categorical feature is Nominal?
# A) city is Nominal

### **Step 4 Choosing the Correct Preprocessing Technique**

Without writing any preprocessing code, decide which preprocessing technique should be applied to every feature.

----------------------------------------------------------------------
#####Complete the below table dataframe in the next code cell and enter the correct preprocessing technique and justification in the "" string
----------------------------------------------------------------------

In [12]:
table = pd.DataFrame({
    "Column": ["Age", "Salary", "Experience", "Gender", "Education", "City"],
    "Feature Type": ["Numerical", "Numerical", "Numerical", "labelencode", "Ordinal", "Nominal"],
    "Selected_Preprocessing_Technique": ["Standradization", "Robust scalar", "standradization", "Binary", "Ordinal", "Nominal"],
    "Justification": ["Age has no extreme outliers and is approximately normally distributed.", "Transformation Salary contains a large outlier (500000), so RobustScaler reduces its influence, while Log Transformation reduces the skewness caused by the outlier.", "Experience increases gradually without significant outliers, making StandardScaler appropriate.", "Gender has only two features so we use the binary encoding", "Education is in order like 10,inter,Btech so there is an order so thats why we use the ordinal encoding", "city are nomianal there is no order for city so we use the Nominal Encoding"]
})

table

,Column,Feature Type,Selected_Preprocessing_Technique,Justification
0,Age,Numerical,Standradization,Age has no extreme outliers and is approximate...
1,Salary,Numerical,Robust scalar,Transformation Salary contains a large outlier...
2,Experience,Numerical,standradization,Experience increases gradually without signifi...
3,Gender,labelencode,Binary,Gender has only two features so we use the bin...
4,Education,Ordinal,Ordinal,"Education is in order like 10,inter,Btech so t..."
5,City,Nominal,Nominal,city are nomianal there is no order for city s...

### **Step 5  StandardScaler**

Read the official [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) for StandardScaler.

Before writing any code, answer the following questions:
1) Why do we need StandardScaler?
2) Which columns should be standardized?
3) What do you think StandardScaler learns during fit()?
4) Which attributes do you expect to see after fitting?

#### write your answers for step-5 here

1. StandardScaler is used to scale numerical features so that they have:

Mean = 0
Standard Deviation = 1

This prevents features with larger values from dominating the model and helps many machine learning algorithms converge faster and perform better.

2. Only numerical columns that are continuous and on different scales.
   Age,Salary,Experience are standardized

3. During fit(), StandardScaler does not change the data. It only calculates and stores the statistics needed for scaling.

It learns:
The mean of each numerical feature.
The standard deviation of each numerical feature.

These values are later used during transform().

4. we can see mean,standard deviation,varince

### **Step 6  Apply standard scaler to the features for which standardization is required**

1) Create the scaler.

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

2) Fit the scaler only on the feature(s) you selected.

In [14]:
standard_scaler = scaler.fit(numerical_features[['Age']])

3) What do you think this scaler has learned during fit()?

In [15]:
# code here
# print scaler.mean_
print(scaler.mean_)
#print scaler.scale_
print(scaler.scale_)

[34.8]
[11.7541482]

4) Use the scaler.fit_transform and scaler.transform, What did you observe?

In [16]:
print(scaler.transform(numerical_features[['Age']]))

print()

Scaled_df = pd.DataFrame(
    scaler.transform(numerical_features[['Age']]),
    columns=['Age']
)

Scaled_df

[[-1.42928264]
 [-1.08897725]
 [-0.83374821]
 [-0.57851916]
 [-0.40836647]
 [ 0.01701527]
 [ 0.44239701]
 [ 0.86777875]
 [ 1.29316049]
 [ 1.71854222]]

        Age
0 -1.429283
1 -1.088977
2 -0.833748
3 -0.578519
4 -0.408366
5  0.017015
6  0.442397
7  0.867779
8  1.293160
9  1.718542

## There is a difference transform gives upto 8 decimal vales but fit_transform givs upto 6 decimals only

### **Step 8  Apply MinMax and Robust scaler to the features for which they are required**

In [17]:
from sklearn.preprocessing import MinMaxScaler,RobustScaler

minmax = MinMaxScaler()
robust = RobustScaler()

Scaled_df['Salary'] = robust.fit_transform(numerical_features[['Salary']])
Scaled_df['Experience'] = minmax.fit_transform(numerical_features[['Experience']])

Scaled_df

        Age     Salary  Experience
0 -1.429283  -0.672269        0.00
1 -1.088977  -0.571429        0.05
2 -0.833748  -0.436975        0.10
3 -0.578519  -0.336134        0.15
4 -0.408366  -0.100840        0.25
5  0.017015   0.100840        0.35
6  0.442397   0.336134        0.50
7  0.867779   0.672269        0.60
8  1.293160   0.907563        0.75
9  1.718542  15.294118        1.00

### **Step 9 Fit a LabelEncoder on the columns where they are required?**

Read the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

1) Why is LabelEncoder suitable for the Gender column?
2) What do you think LabelEncoder learns during fit()?
3) Which attribute should contain the learned information?

1) fit the encoder

In [18]:
# code here
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(df['Gender'])
# check encoder.classes_

LabelEncoder()

In [19]:
print(encoder.classes_)

['Female' 'Male']

2) transform the features

In [20]:
# code here
print(encoder.transform(df['Gender']))
# after that use encoder.inverse_transform
print(encoder.inverse_transform(encoder.transform(df['Gender'])))

[1 0 1 0 1 0 1 0 1 0]
['Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male'
 'Female']

3) Use fit_transform

In [21]:
# code here
Scaled_df['Gender'] = encoder.fit_transform(categorical_features[['Gender']])
Scaled_df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

        Age     Salary  Experience  Gender
0 -1.429283  -0.672269        0.00       1
1 -1.088977  -0.571429        0.05       0
2 -0.833748  -0.436975        0.10       1
3 -0.578519  -0.336134        0.15       0
4 -0.408366  -0.100840        0.25       1
5  0.017015   0.100840        0.35       0
6  0.442397   0.336134        0.50       1
7  0.867779   0.672269        0.60       0
8  1.293160   0.907563        0.75       1
9  1.718542  15.294118        1.00       0

### **Step 9 Then repeat the same workflow for OrdinalEncoder on columns where it is required**
Go through the documentation yourself

In [22]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['High School', 'Bachelor', 'Master', 'PhD']])
print(encoder.fit(categorical_features[['Education']]))
print(encoder.transform(categorical_features[['Education']]))
print(encoder.inverse_transform(encoder.transform(categorical_features[['Education']])))
Scaled_df['Education'] = encoder.fit_transform(categorical_features[['Education']])
Scaled_df

OrdinalEncoder(categories=[['High School', 'Bachelor', 'Master', 'PhD']])
[[0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [2.]
 [3.]
 [3.]]
[['High School']
 ['Bachelor']
 ['Bachelor']
 ['Master']
 ['Master']
 ['PhD']
 ['Bachelor']
 ['Master']
 ['PhD']
 ['PhD']]

        Age     Salary  Experience  Gender  Education
0 -1.429283  -0.672269        0.00       1        0.0
1 -1.088977  -0.571429        0.05       0        1.0
2 -0.833748  -0.436975        0.10       1        1.0
3 -0.578519  -0.336134        0.15       0        2.0
4 -0.408366  -0.100840        0.25       1        2.0
5  0.017015   0.100840        0.35       0        3.0
6  0.442397   0.336134        0.50       1        1.0
7  0.867779   0.672269        0.60       0        2.0
8  1.293160   0.907563        0.75       1        3.0
9  1.718542  15.294118        1.00       0        3.0

### **Step 10 Now repeat the same workflow for OneHotEncoder on columns where it is required**

In [23]:
categorical_features[['City']]

        City
0  Hyderabad
1      Delhi
2     Mumbai
3      Delhi
4  Hyderabad
5    Chennai
6     Mumbai
7      Delhi
8  Hyderabad
9    Chennai

In [24]:
# code here
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
print(encoder.fit(categorical_features[['City']]))
print(encoder.transform(categorical_features[['City']]))
# after fitting the encoder check encoder.categories_
print(encoder.categories_)
# check encoder.get_feature_names_out()
print(encoder.get_feature_names_out())

OneHotEncoder()
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (10, 4)>
  Coords	Values
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (3, 1)	1.0
  (4, 2)	1.0
  (5, 0)	1.0
  (6, 3)	1.0
  (7, 1)	1.0
  (8, 2)	1.0
  (9, 0)	1.0
[array(['Chennai', 'Delhi', 'Hyderabad', 'Mumbai'], dtype=object)]
['City_Chennai' 'City_Delhi' 'City_Hyderabad' 'City_Mumbai']

In [25]:
city_df = pd.DataFrame(encoder.fit_transform(categorical_features[['City']]).toarray(),columns =['City_Chennai','City_Delhi','City_Hyderabad','City_Mumbai'] )
Scaled_df = pd.concat([Scaled_df,city_df],axis=1)
Scaled_df

,Age,Salary,Experience,Gender,Education,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai
0,-1.429283,-0.672269,0.00,1,0.0,0.0,0.0,1.0,0.0
1,-1.088977,-0.571429,0.05,0,1.0,0.0,1.0,0.0,0.0
2,-0.833748,-0.436975,0.10,1,1.0,0.0,0.0,0.0,1.0
3,-0.578519,-0.336134,0.15,0,2.0,0.0,1.0,0.0,0.0
4,-0.408366,-0.100840,0.25,1,2.0,0.0,0.0,1.0,0.0
5,0.017015,0.100840,0.35,0,3.0,1.0,0.0,0.0,0.0
6,0.442397,0.336134,0.50,1,1.0,0.0,0.0,0.0,1.0
7,0.867779,0.672269,0.60,0,2.0,0.0,1.0,0.0,0.0
8,1.293160,0.907563,0.75,1,3.0,0.0,0.0,1.0,0.0
9,1.718542,15.294118,1.00,0,3.0,1.0,0.0,0.0,0.0

### **Final Step, Now that you understand every preprocessing technique individually**

1) build a single preprocessing pipeline.

2) Finally, combine them using ColumnTransformer, refer to    [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html) and transform the complete dataset.

In [26]:
# Step1

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    OrdinalEncoder,
    OneHotEncoder
)

# Numerical columns
standard_features = ['Age']
robust_features = ['Salary']
minmax_features = ['Experience']

# Ordinal column
ordinal_features = ['Education']

# One-Hot Encoding column
onehot_features = ['City']

# Binary column
gender_features = ['Gender']

standard_transformer = StandardScaler()

robust_transformer = RobustScaler()

minmax_transformer = MinMaxScaler()

ordinal_transformer = OrdinalEncoder(
    categories=[['High School', 'Bachelor', 'Master', 'PhD']]
)

onehot_transformer = OneHotEncoder(
    drop='first',
    sparse_output=False
)

# Binary Encoding using OrdinalEncoder
gender_transformer = OrdinalEncoder(
    categories=[['Male', 'Female']]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('age_scaling', standard_transformer, standard_features),
        ('salary_scaling', robust_transformer, robust_features),
        ('experience_scaling', minmax_transformer, minmax_features),
        ('education_encoding', ordinal_transformer, ordinal_features),
        ('gender_encoding', gender_transformer, gender_features),
        ('city_encoding', onehot_transformer, onehot_features)
    ]
)

processed_data = preprocessor.fit_transform(df)

city_columns = preprocessor.named_transformers_[
    'city_encoding'
].get_feature_names_out(['City'])

final_columns = [
    'Age',
    'Salary',
    'Experience',
    'Education',
    'Gender'
] + list(city_columns)

processed_df = pd.DataFrame(
    processed_data,
    columns=final_columns
)

print(processed_df)

        Age     Salary  Experience  Education  Gender  City_Delhi  \
0 -1.429283  -0.672269        0.00        0.0     0.0         0.0
1 -1.088977  -0.571429        0.05        1.0     1.0         1.0
2 -0.833748  -0.436975        0.10        1.0     0.0         0.0
3 -0.578519  -0.336134        0.15        2.0     1.0         1.0
4 -0.408366  -0.100840        0.25        2.0     0.0         0.0
5  0.017015   0.100840        0.35        3.0     1.0         0.0
6  0.442397   0.336134        0.50        1.0     0.0         0.0
7  0.867779   0.672269        0.60        2.0     1.0         1.0
8  1.293160   0.907563        0.75        3.0     0.0         0.0
9  1.718542  15.294118        1.00        3.0     1.0         0.0

   City_Hyderabad  City_Mumbai
0             1.0          0.0
1             0.0          0.0
2             0.0          1.0
3             0.0          0.0
4             1.0          0.0
5             0.0          0.0
6             0.0          1.0
7             0.0          0.0
8             1.0          0.0
9             0.0          0.0